# runtime: nodejs18

# instance_class: F1

# automatic_scaling:
#   min_instances: 0
#   max_instances: 2

# handlers:
#   - url: /.*
#     script: auto
#     secure: always

# env_variables:
#   NODE_ENV: "production"

runtime: nodejs24 # Or whatever version you have installed
instance_class: F1
env_variables:
  NODE_ENV: "production"